name: Main

on: [workflow_dispatch, pull_request]

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      # needed for the checkout action
      contents: read
      # needed to annotate the files in a pull request with comments
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: devops-actions/actionlint@v0.1.2
    
      - name: Access secres
        run: |
          echo "Secret: [${{ secrets.CONNECTION_STRING }}]"
          echo "Var: [${{ vars.MY_VAR }}]"
      - name: Write messages to the log
        run: |
          echo "::debug::This is a debug message"
          echo "::warning file=app.js,line=1,col=51,endColumn=52::Missing semicolon"
          echo "::error file=app.js,line=2,col=1,endColumn=7::Error in app.js"
          
      - id: sets-a-secret
        name: Generate, mask, and output a secret
        run: |
          the_secret='123456'
          echo "::add-mask::$the_secret"
          echo "$the_secret"
          echo "secret-number=$the_secret" >> "$GITHUB_OUTPUT"
      - name: Use that secret output (protected by a mask)
        run: |
          echo "the secret number is ${{ steps.sets-a-secret.outputs.secret-number }}"
          echo "${{ steps.sets-a-secret.outputs.secret-number }}" | sed 's/./& /g'

