name: My First Workflow

on: 
  push:
    branches: 
      - main
  
  repository_dispatch:
    types: [event1, event2]
    
  workflow_dispatch:
    inputs:
      homedrive:
        description: 'The home drive on the machine'
        required: true
      logLevel:
        description: 'Log level'
        default: 'warning' 
        type: choice
        options:
        - info
        - warning
        - debug 
      tag:
        description: 'Apply tag after successfull test run'
        required: true 
        type: boolean 
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true 
  
jobs:
  MyFirstJob:
    runs-on: ubuntu-latest
    
    steps:
      - run: |
          echo "Homedrive: ${{ inputs.homedrive }}"
          echo "Log level: ${{ inputs.logLevel }}"
          echo "Tag source: ${{ inputs.tag }}"
          echo "Environment ${{ inputs.environment }}"
        name: Workflow Inputs
        if: ${{ github.event_name == 'workflow_dispatch' }}
      
      - run: |
          echo "Payload: ${{ toJSON(github.event.client_payload) }}"
        name: Payload
        if: ${{ github.event_name == 'repository_dispatch' }}
      
      
      - run: echo "👋 Hello World!"
      
      - name: Checkout
        uses: actions/checkout@v4 
      
      - name: List files in repository
        run: |
          echo "The repository ${{ github.repository }} contains th efollowing files:"
          tree
      
